### ISSUE TITLE
react example doesn't work with standalone environment

### ISSUE THREAD

**Issue by FindDefinition** [TypeFox/monaco-languageclient#528]
[codesandbox](https://codesandbox.io/p/sandbox/angry-driscoll-vpn7t6?file=/src/EditorCustom.tsx:49,32). 
I'm using client@5.0.1 and it works well. after I upgrade client to 6.x, I have encountered many errors:
1. `Cannot read properties of undefined (reading 'match')` if theme unset
2. `Cannot read properties of undefined (reading 'getRelativeLuminance')` if theme set
3. `TypeError: extensionService.deltaExtensions is not a function` if I put `initServices` in effect of `Editor`
4. `Cannot have two contributions with the same id editor.contrib.referencesController` even if I replace all `import * as monaco from "monaco-editor"` with `import * as monaco from "monaco-editor/esm/vs/editor/editor.api"`

Now I create a minimal environment to debug the problem, I find that the react example in this project doesn't work in a flesh environment.
any ideas?

**Comment by kaisalmen** [comment]
@FindDefinition I guess the treemending did not work: https://github.com/TypeFox/monaco-languageclient#using-monaco-languageclient
@CGNonofr does that work flawlessly in codesandbox, any idea?

**Comment by CGNonofr** [comment]
The last item shouldn't be an issue anymore. The cause was something importing 'monaco-editor' directly somewhere (a lib?)

Regarding the other error, it's hard to tell, it's probably a wrong service initialization

**Comment by kaisalmen** [comment]
@FindDefinition don't know why it fails in codesandbox. It seems the treemending is not applied. Are you able to wipe node_module and force re-installation? See: https://github.com/TypeFox/monaco-languageclient/issues/522

**Comment by FindDefinition** [comment]
@kaisalmen I download the sandbox to local environment and install everything from scratch, the problem still exists (`Cannot read properties of undefined (reading 'match')`). then I try npm instead of yarn, still exists.
I decide to stay at client@5.0.1 because of those errors and large bundle size (+780KB after 5.0.1 -> 6.4.2). look forward to `monaco-languageclient` 7.x...

**Comment by LiuJi-Jim** [comment]
Same problem. Do you guys find any way to solve this?
I'm planning to use monaco-editor 0.41 since some of my teammates need the new features. That's why I really need to use monaco-languageclient@^6.4 😢

**Comment by kaisalmen** [comment]
@FindDefinition and @LiuJi-Jim do you have the same problems when you test the react example from this repo?
https://github.com/TypeFox/monaco-languageclient/tree/main/packages/examples/main/src/react

**Comment by LiuJi-Jim** [comment]
@kaisalmen I got `ELIFECYCLE`  errors like below when I'm trying to run the react example.

> ➜  main git:(main) ✗ pnpm i
> Packages: +140
> ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> Packages are hard linked from the content-addressable store to the virtual store.
>   Content-addressable store is at: /Users/jimliu/Library/pnpm/store/v3
>   Virtual store is at:             node_modules/.pnpm
> Downloading registry.npmjs.org/typescript/5.2.2: 7.23 MB/7.23 MB, done
> Progress: resolved 140, reused 115, downloaded 25, added 140, done
> node_modules/.pnpm/monaco-languageclient@6.4.4_monaco-editor@0.41.0/node_modules/monaco-languageclient: Running postinstall script...
>  ELIFECYCLE  Command failed.

**My dev env**

- pnpm -v // 8.6.0 and this is required for our project.
- node -v1 // 18.13.0
- monaco-languageclient@6.4.4 -> cloned this repo and nothing's changed
- pwd -> /Users/jimliu/work/src/github/monaco-languageclient/packages/examples/main

Do you think that the `monaco-treemending` still doesn't work well with pnpm? I've tried some ways shared in #492 but I didn't make it.

**Comment by LiuJi-Jim** [comment]
verify/pnpm and verify/vite both work fine independently. But when I combine vite(vue) + pnpm + monaco-editor-workers + monaco-treemending altoghether, problem happen.

Here is a code sandbox of my minimal demo
https://codesandbox.io/p/sandbox/bold-microservice-nm3cjn?file=/src/monaco/editor.ts:11,1

<img width="2580" alt="image" src="https://github.com/TypeFox/monaco-languageclient/assets/2749742/bd68169b-64aa-4d99-a10d-60eba53a17c5">

Notice these lines
```
import "monaco-editor/esm/vs/basic-languages/typescript/typescript.contribution.js";
import "monaco-editor/esm/vs/language/typescript/monaco.contribution.js";
```
importing the typescript language support might be the source of the problem. But I do need them since if I comment these two lines, I will get no syntax highlighting at all.

**Comment by kaisalmen** [comment]
@LiuJi-Jim if you want to use monarch based syntax highlighting you can't enable theme and textmate service. If you comment them or set them to false your sandbox works:
```typescript
enableThemeService: false
enableTextmateService: false,
```
This is documented here:
https://github.com/CodinGame/monaco-vscode-api#monaco-standalone-services
But we need to improve our documentation here as well. I have just tracked this in #515

**Comment by LiuJi-Jim** [comment]
@kaisalmen It works! Thank you very much!
