### ISSUE TITLE
cannot build example due to type error

### ISSUE THREAD

**Issue by MassMessage** [TypeFox/monaco-languageclient#283]
I'm trying to build the example from the /example folder but I can't figure out why I'm getting below error. I think I'm using very same module, version and everything. I did install them using:

```
npm install monaco-editor
npm i monaco-languageclient
```

but I when do run ```yarn``` I get this error:

`src/client.ts:32:24 - error TS2345: Argument of type 'import("path/to/project/monaco-languageclient/example/node_modules/monaco-editor/esm/vs/editor/editor.api").editor.IStandaloneCodeEditor' is not assignable to parameter of type 'monaco.editor.IStandaloneCodeEditor'.`

The imports are the following:

```
import { listen, MessageConnection } from 'vscode-ws-jsonrpc';
import {
    MonacoLanguageClient, CloseAction, ErrorAction,
    MonacoServices, createConnection
} from 'monaco-languageclient';
import normalizeUrl = require('normalize-url');
import * as monaco from 'monaco-editor'
```

and the lines causing the issue:

```
const editor = monaco.editor.create(document.getElementById("container")!, {
    model: monaco.editor.createModel(value, 'typescript', monaco.Uri.parse('file:///abs/path/to/demo/ts/file.ts')),
    glyphMargin: true,
    theme: "vs-dark",
    lightbulb: {
        enabled: true
    }
});

// install Monaco language client services
MonacoServices.install(editor,{rootUri: "file:///abs/path/to/demo/ts"});
```

here's the full client.ts source code:

```
import { listen, MessageConnection } from 'vscode-ws-jsonrpc';
import {
    MonacoLanguageClient, CloseAction, ErrorAction,
    MonacoServices, createConnection
} from 'monaco-languageclient';
import normalizeUrl = require('normalize-url');
import * as monaco from 'monaco-editor'

const ReconnectingWebSocket = require('reconnecting-websocket');

// register Monaco languages
monaco.languages.register({
    id: 'typescript',
    extensions: ['.ts'],
    aliases: ['TypeScript','ts','TS','Typescript','typescript']
})

// create Monaco editor
const value = `{
    "$schema": "http://json.schemastore.org/coffeelint",
    "line_endings": "unix"
}`;
const editor = monaco.editor.create(document.getElementById("container")!, {
    model: monaco.editor.createModel(value, 'typescript', monaco.Uri.parse('file:///abs/path/to/demo/ts/file.ts')),
    glyphMargin: true,
    theme: "vs-dark",
    lightbulb: {
        enabled: true
    }
});

// install Monaco language client services
MonacoServices.install(editor,{rootUri: "file:///abs/path/to/demo/ts"});

// create the web socket
const url = createUrl('ws://localhost:3000/ts')
const webSocket = createWebSocket(url);
// listen when the web socket is opened
listen({
    webSocket,
    onConnection: connection => {
        // create and start the language client
        const languageClient = createLanguageClient(connection);
        const disposable = languageClient.start();
        connection.onClose(() => disposable.dispose());
    }
});

function createLanguageClient(connection: MessageConnection): MonacoLanguageClient {
    return new MonacoLanguageClient({
        name: "Sample Language Client",
        clientOptions: {
            // use a language id as a document selector
            documentSelector: ['typescript'],
            // disable the default error handler
            errorHandler: {
                error: () => ErrorAction.Continue,
                closed: () => CloseAction.DoNotRestart
            }
        },
        // create a language client connection from the JSON RPC connection on demand
        connectionProvider: {
            get: (errorHandler, closeHandler) => {
                return Promise.resolve(createConnection(connection, errorHandler, closeHandler))
            }
        }
    });
}

function createUrl(path: string): string {
    return normalizeUrl(path);
}

function createWebSocket(url: string): WebSocket {
    const socketOptions = {
        maxReconnectionDelay: 10000,
        minReconnectionDelay: 1000,
        reconnectionDelayGrowFactor: 1.3,
        connectionTimeout: 10000,
        maxRetries: Infinity,
        debug: false
    };
    return new ReconnectingWebSocket(url, [], socketOptions);
}
```

Why am I getting this type error and how do I fix this?

**Comment by rspeyer** [comment]
I was only able to fix this by modifying `monaco-languageclient` itself to use `monaco-editor` instead of `monaco-editor-core`. The two don't seem directly compatible anymore. I attempted to `@ts-ignore` the mismatch, but things did not behave properly further along.

**Comment by MassMessage** [comment]
> 
> 
> I was only able to fix this by modifying `monaco-languageclient` itself to use `monaco-editor` instead of `monaco-editor-core`. The two don't seem directly compatible anymore. I attempted to `@ts-ignore` the mismatch, but things did not behave properly further along.

This seems very bad. I think I can't modify `monaco-languageclient` itself and make the app stuck at this version, even if this was working properly. Can I get theming support and syntax highlight somewhat with monaco core editor?

**Comment by arunganesh-a** [comment]
is there any update on this, even I am struck with the same issue.

**Comment by MassMessage** [comment]
> 
> 
> is there any update on this, even I am struck with the same issue.

can you build this with old version of monaco-languageclient and monaco editor? even with +1yo version I can't make this work. I'm stuck

**Comment by MassMessage** [comment]
> 
> 
> is there any update on this, even I am struck with the same issue.

can you build this with old version of monaco-languageclient and monaco editor? even with +1yo version I can't make this work. I'm stuck too

**Comment by MassMessage** [comment]
> 
> 
> I was only able to fix this by modifying `monaco-languageclient` itself to use `monaco-editor` instead of `monaco-editor-core`. The two don't seem directly compatible anymore. I attempted to `@ts-ignore` the mismatch, but things did not behave properly further along.

Do you have any idea how hard would be to fix this? it's something that did change in the new monaco editor api and the monaco language client didn't catch up? I think no big changes did happen so maybe it isn't that hard to fix?

**Comment by arunganesh-a** [comment]
@MassMessage  might not be an ideal solution. I got it to working with monaco editor 0.27.0 and language client 0.13.0,
in MonacoServices.install  use monaco instead of editor and type cast 
`MonacoServices.install(monaco` as any);`

**Comment by rspeyer** [comment]
I have been able to work around this as follows. Instead of importing the entire `monaco-editor`, I am doing:
`import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';`

This is prudent from a size-of-bundle perspective as well, and supports theming, etc. as well. I can execute `MonacoServices.install(monaco)` with no errors.

Using:
```
    "monaco-editor": "^0.26.1",
    "monaco-languageclient": "^0.13.1-next.9",
```

**Comment by MassMessage** [comment]
@rspeyer @arunganesh-a how did you guys managed to compile with older version? I feel stupid but I'm still getting the error with the version monaco version v0.26.1 and monaco languageclient v0.13.1-next9.  importing monaco as `import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';` the modules version:

```
$ npm list
+-- @codingame/monaco-jsonrpc@0.3.1
+-- express@4.17.1
+-- file-loader@4.3.0
+-- monaco-editor@0.26.1
+-- monaco-languageclient@0.13.1-next.9
+-- normalize-url@2.0.1
+-- reconnecting-websocket@3.2.2
+-- request-light@0.2.5
+-- vscode-json-languageservice@4.1.7
+-- vscode-languageserver@7.0.0
+-- vscode-uri@3.0.2
`-- ws@5.2.3
```

still the same error:

```
src/client.ts:34:24 - error TS2345: Argument of type 'IStandaloneCodeEditor' is not assignable to parameter of type 'typeof import("C:/path/project/monaco-languageclient/node_modules/monaco-editor-core/esm/vs/editor/editor.api")'.
  Type 'IStandaloneCodeEditor' is missing the following properties from type 'typeof import("C:/path/project/monaco-languageclient/node_modules/monaco-editor-core/esm/vs/editor/editor.api")': Emitter, MarkerTag, MarkerSeverity, CancellationTokenSource, and 10 more.
```
What am I missing?

**Comment by MassMessage** [comment]
The issue was solved! thanks to [@ futur:](https://stackoverflow.com/a/68877450/800123)

> The issue appears to be a conflict between the monaco namespace provided by monaco-editor and the namespace of the same name provided by monaco-editor-core. When both are installed as dependencies, TypeScript seems to assume that monaco.editor.IStandaloneCodeEditor is referring to the latter, which causes issues since the created monaco.editor is imported from the former.
> 
> To resolve this, removing monaco-editor-core as a dependency fixes the confusion and uses the correct typings for monaco.editor.IStandaloneCodeEditor.
